deimos/urls.py
from . import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.eventos.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/eventos/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid
import qrcode

# Create your models here.

ESTATUS = (
    ('A','Activo'),
    ('I','Inactivo')
)

class Tipo_Usuario (models.Model):
    nombre = models.CharField(max_length=20)
    estatus = models.CharField(max_length=1, choices=ESTATUS, default='A')

    def __str__(self):
        return self.nombre

class Usuario (AbstractUser):
    nombre = models.CharField(max_length=25,null=True,blank=True)
    apellido = models.CharField(max_length=25,null=True,blank=True)
    tipo_user = models.ForeignKey(Tipo_Usuario,on_delete=models.CASCADE,null=True,blank=True,default=3)
    SEXO = (
        ('M','Masculino'),
        ('F','Femenino'),
        ('O','Otro'),
    )
    sexo = models.CharField(max_length=1,choices=SEXO,null=True,blank=True)
    fecha_nacimiento = models.DateField(null=True,blank=True)
    correo = models.EmailField(null=True,blank=True)
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='A')

class Medio_Pago(models.Model):
    nombre = models.CharField(max_length=50)
    TIPOS = (
        ('D','Divisa'),
        ('N','Nacional')
    )
    tipo = models.CharField(max_length=1,choices=TIPOS)
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='A')

class Organizacion(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    ubicacion = models.CharField(max_length=50)
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='A')

class Usuario_Organizacion(models.Model):
    usuario = models.ForeignKey(Usuario,on_delete=models.CASCADE)
    organizacion = models.ForeignKey(Organizacion,on_delete=models.CASCADE)
    puesto = models.CharField(max_length=50)

class Evento(models.Model):
    nombre = models.CharField(max_length=100)
    fecha = models.DateField()
    hora = models.TimeField()
    lugar = models.CharField(max_length=25)
    aforo = models.IntegerField()
    precio = models.FloatField()
    descripcion = models.CharField(max_length=500)
    ESTATUS_EVENTO = (
        ('P','Preventa'),
        ('V','Venta'),
        ('F','Finalizado'),
        ('C','Cancelado')
    )
    estatus = models.CharField(max_length=1,choices=ESTATUS_EVENTO, default='V')

    def EntradasVendidas(self):
        return Entrada.objects.filter(evento=self).count()

    def EntradasDisponibles(self):
        return self.aforo-self.EntradasVendidas()

    def MontoRecaudado(self):
        return self.EntradasVendidas()*self.precio

class Pago(models.Model):
    medio_pago = models.ForeignKey(Medio_Pago,models.CASCADE)
    referencia = models.CharField(max_length=25)
    comprobante = models.ImageField(upload_to='comprobantes/', default='comprobantes/default.png')
    ESTATUS_PAGO = (
        ('P','Pendiente de aprobación'),
        ('A','Aprobado')
    )
    estatus = models.CharField(max_length=1,choices=ESTATUS_PAGO,default='A')

class Entrada(models.Model):
    id = models.CharField(max_length=100,primary_key=True,default=uuid.uuid4)
    evento = models.ForeignKey(Evento, models.CASCADE)
    usuario = models.ForeignKey(Usuario, models.CASCADE)
    forma_pago = models.ForeignKey(Pago, models.CASCADE)
    fecha = models.DateField(auto_now=True)
    costo = models.FloatField()
    cantidad = models.IntegerField()
    qr = models.ImageField(upload_to='media/qr/', blank=True, null=True)
    ESTATUS_ENTRADA = (
        ('P','Pendiente por aprobación'),
        ('A','Aprobada'),
        ('F','Utilizada')
    )
    estatus = models.CharField(max_length=1,choices=ESTATUS_ENTRADA,default='A')

    def MontoTotal(self):
        return self.costo * self.cantidad

class Asiento(models.Model):
    entrada = models.ForeignKey(Entrada, models.CASCADE)
    fila = models.CharField(max_length=1)
    numero = models.IntegerField()

class Registro_Participacion(models.Model):
    entrada = models.ForeignKey(Entrada,models.CASCADE,blank=True, null=True)
    encargado = models.ForeignKey(Usuario,models.CASCADE,blank=True, null=True)
    fecha = models.DateField(auto_now=True)
    qr = models.ImageField(upload_to='registro/', blank=True, null=True)
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='A')

## SEÑAL PARA EL CÓDIGO QR

@receiver(post_save,sender=Entrada)
def ImagenQR(sender, instance, **kwargs):
    if instance.qr == None:
        img = qrcode.make(instance.id)
        with open('/home/gabriel/Deimos/media/qr/' + str(instance.id) + '.png', 'wb') as f:
            img.save(f)
        instance.qr = 'qr/' + str(instance.id) + '.png'
        instance.save()

apps/eventos/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario, Registro_Participacion

class BaseCrearUsuario(UserCreationForm):

    class Meta:
        model = Usuario

        fields = [
            'username',
            'nombre',
            'correo',
            'sexo',
            'fecha_nacimiento',
            'password1',
            'password2',
        ]

class CrearUsuario(BaseCrearUsuario):
    organizacion = forms.CharField()
    puesto = forms.CharField()

    class Meta(BaseCrearUsuario.Meta):
        fields = BaseCrearUsuario.Meta.fields + ['organizacion','puesto']

class ProcesarEntrada(forms.ModelForm):

    class Meta:
        model = Registro_Participacion

        fields = [
            'qr'
        ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="has-navbar-fixed-top has-background-grey-lighter is-family-sans-serif">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Deimos - ¡Compra tus entradas para tus eventos!</title>
    <link rel="icon" type="image/png" href="{% static 'img/icono.png' %}">
    <link rel="stylesheet" href="{% static 'css/bulma_deimos.css' %}">
    <link rel="stylesheet" href="{% static 'css/swal.css' %}">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

{% include "navbar.html" %}

<body>
    {% block contenido %}

    {% endblock contenido %}

    {% include "footer.html" %}

</body>
{% block js %}

{% endblock js %}
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script src="{% static 'js/deimos.js' %}"></script>
</html>

templates/consultar_entrada.html
{% extends "base/base.html" %}
{% block contenido %}
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title is-family-primary">
                Consultar tu entrada.
            </h1>
            <h2 class="subtitle is-family-secondary has-text-justified">
                Esta interfaz te permite consultar la entrada de tu elección.
            </h2>
        </div>
    </div>
</section>

<section class="section">
    <div class="columns is-centered">
        <div class="column is-four-fifths">
            <div class="content">
                <div class="card">
                    <div class="card-content">
                        <div class="content">
                            <div class="title is-family-primary has-text-justified">
                                Tu entrada para: "{{entrada.evento.nombre}}"
                            </div>
                            <div class="subtitle is-family-secondary has-text-justified">
                                "{{entrada.evento.descripcion}}"
                            </div>
                        </div>
                        <div class="columns is-centered has-text-centered">
                            <div class="column has-background-light">
                                <div class="subtitle is-family-primary is-5"><strong>Datos de
                                        la Entrada:</strong></div>
                                <p><strong>Fecha de compra: </strong>{{entrada.fecha}}</p>
                                <p><strong>Cantidad comprada: </strong>{{entrada.cantidad}}
                                </p>
                                <p><strong>Asientos: </strong>{% for asiento in asientos %}{{asiento.fila}}-{{asiento.numero}} {% endfor %}
                                </p>
                                <p><strong>Precio Unitario: </strong>Bs. {{entrada.costo}}</p>
                                <p><strong>Total Pagado: </strong>Bs. {{entrada.MontoTotal}}</p>
                                <p><strong>Estatus de la Entrada:
                                    </strong>{{entrada.get_estatus_display}}</p>
                            </div>
                            <div class="column">
                                <div class="subtitle is-family-primary is-5"><strong>Datos de
                                        Pago:</strong></div>
                                <p><strong>ID del pago: </strong>{{entrada.forma_pago.id}}</p>
                                <p><strong>Referencia: </strong>{{entrada.forma_pago.referencia}}
                                </p>
                                <p><strong>Medio de Pago: </strong>{{entrada.forma_pago.medio_pago.nombre}}</p>
                                <p><strong>Comprobante: </strong><a href="{{entrada.forma_pago.comprobante.url}}"
                                        class="button is-primary is-small">Ver</a></p>
                                <p><strong>Estatus del Pago:
                                    </strong>{{entrada.forma_pago.get_estatus_display}}</p>
                            </div>
                            <div class="column has-background-light">
                                <div class="subtitle is-family-primary is-5"><strong>Datos del Evento:</strong></div>
                                <p><strong>Lugar: </strong>{{entrada.evento.lugar}}</p>
                                <p><strong>Fecha: </strong>{{entrada.evento.fecha}}</p>
                                <p><strong>Hora: </strong>{{entrada.evento.hora|time:'h:i a'}}</p>
                                <p><strong>Estado del Evento: </strong>{{entrada.evento.get_estatus_display}}</p>
                            </div>
                        </div>
                        <div class="has-text-centered has-background-light">
                            <div class="subtitle is-family-primary is-4"><strong>Código QR
                                    de tu entrada:</strong></div>
                            <img src="{{entrada.qr.url}}" style="margin-top:-20px;"></img>
                            <div clas="is-primary is-7">El día del evento, muestra este código al recepcionista que
                                estará en la puerta.</div>
                        </div>
                    </div>
                    <div class="has-text-centered">
                        <a class="button is-danger"
                            href="{% if user.tipo_user.id == 1 %}{% url 'entradas_vendidas' %}{% else %}{% url 'ticket' %}{% endif %}">Volver
                            al listado</a>
                    </div>
                    <br />
                    <br />
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock contenido %}

templates/entrada_procesada.html
{% extends "base/base.html" %}
{% block contenido %}
<section class="hero is-success is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title is-family-primary">
                ¡Entrada procesada con éxito!
            </h1>
            <h2 class="subtitle is-family-secondary has-text-justified">
                La entrada es válida. Puedes acceder al recinto.
            </h2>
        </div>
    </div>
</section>

<section class="section">
    <div class="columns is-centered">
        <div class="column is-four-fifths">
            <div class="content">
                <div class="card">
                    <div class="card-content">
                        <div class="content">
                            <div class="title is-family-primary has-text-justified">
                                La entrada es para: "{{entrada.evento.nombre}}"
                            </div>
                        </div>
                        <div class="columns is-centered has-text-centered">
                            <div class="column has-background-light">
                                <div class="subtitle is-family-primary is-5"><strong>Datos de
                                        la Entrada:</strong></div>
                                <p><strong>Fecha de compra: </strong>{{entrada.fecha}}</p>
                                <p><strong>Cantidad comprada: </strong>{{entrada.cantidad}}
                                </p>
                                <p><strong>Asientos: </strong>{% for asiento in asientos %}{{asiento.fila}}-{{asiento.numero}} {% endfor %}
                                </p>
                            </div>
                            <div class="column has-background-light">
                                <div class="subtitle is-family-primary is-5"><strong>Datos del Evento:</strong></div>
                                <p><strong>Lugar: </strong>{{entrada.evento.lugar}}</p>
                                <p><strong>Fecha: </strong>{{entrada.evento.fecha}}</p>
                                <p><strong>Hora: </strong>{{entrada.evento.hora|time:'h:i a'}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="has-text-centered">
                        <a class="button is-danger"
                            href="{% url 'process' %}">Seguir procesando</a>
                    </div>
                    <br />
                    <br />
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock contenido %}

templates/entradas.html
{% extends "base/base.html" %}

{% block contenido %}
<section class="hero is-success is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title is-family-primary">
                Mis entradas.
            </h1>
            <h2 class="subtitle is-family-secondary has-text-justified">
                Revisa, confirma y consulta las entradas que has comprado hasta ahora.
            </h2>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        {% if object_list %}
        <table class="table is-striped is-hoverable is-fullwidth">
            <thead class="has-background-dark">
                <th class="has-background-dark has-text-white has-text-centered">Evento</th>
                <th class="has-background-dark has-text-white has-text-centered">Fecha de Compra</th>
                <th class="has-background-dark has-text-white has-text-centered">Cantidad</th>
                <th class="has-background-dark has-text-white has-text-centered">Precio Unitario</th>
                <th class="has-background-dark has-text-white has-text-centered">Total Pagado</th>
                <th class="has-background-dark has-text-white has-text-centered">Opciones</th>
            </thead>
            <tbody>
                {% for entrada in object_list %}
                <tr>
                    <td class="has-text-centered">{{entrada.evento.nombre}}</td>
                    <td class="has-text-centered">{{entrada.fecha}}</td>
                    <td class="has-text-centered">{{entrada.cantidad}}</td>
                    <td class="has-text-centered">Bs. {{entrada.costo}}</td>
                    <td class="has-text-centered">Bs. {{entrada.MontoTotal}}</td>
                    <td class="has-text-centered">
                        <a class="button is-primary" href="{% url 'consultar_entrada' entrada.id %}">Ver</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            {% else %}
            <h1 class="title is-family-primary is-4">Aún no compras entradas. <a href="{% url 'home' %}">¿Deseas comprar
                    alguna?</a></h1>
            {% endif %}
        </table>
    </div>
</section>
{% endblock contenido %}

templates/entradas_vendidas.html
{% extends "base/base.html" %}

{% block contenido %}
<section class="hero is-danger is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title is-family-primary">
                ¡Bienvenido, administrador!
            </h1>
            <h2 class="subtitle is-family-secondary has-text-justified">
                A continuación, te presentamos un listado con las entradas que han sido vendidas por el sistema.
            </h2>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        {% if object_list %}
        <table class="table is-striped is-hoverable is-fullwidth">
            <thead class="has-background-dark">
                <th class="has-background-dark has-text-white has-text-centered">ID</th>
                <th class="has-background-dark has-text-white has-text-centered">Usuario</th>
                <th class="has-background-dark has-text-white has-text-centered">Fecha</th>
                <th class="has-background-dark has-text-white has-text-centered">Evento</th>
                <th class="has-background-dark has-text-white has-text-centered">Forma de Pago</th>
                <th class="has-background-dark has-text-white has-text-centered">Opciones</th>
            </thead>
            <tbody>
                {% for entrada in object_list %}
                <tr>
                    <td class="has-text-centered">{{entrada.id|truncatechars:12}}</td>
                    <td class="has-text-centered">{{entrada.usuario.username}}</td>
                    <td class="has-text-centered">{{entrada.fecha}}</td>
                    <td class="has-text-centered">{{entrada.evento.nombre}}</td>
                    <td class="has-text-centered">{{entrada.forma_pago.medio_pago.nombre}}</td>
                    <td class="has-text-centered">
                        <a class="button is-primary is-small" href="{% url 'consultar_entrada' entrada.id %}">Ver</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="title is-font-primary is-4">
            ¡Oh, no! Aún no has vendido ninguna entrada :'-(
        </div>
        {% endif %}
    </div>
</section>
{% endblock contenido %}

templates/exito_registro.html
{% extends "base/base.html" %}
{% block contenido %}
<div class="content">
    <div class="card has-background-success">
        <div class="card-content">
            <p class="title">
                Registro exitoso
            </p>
            <p class="subtitle">
                Ahora puedes iniciar sesión con tus credenciales.
            </p>
        </div>
        <footer class="card-footer">
            <p class="card-footer-item">
                <span>
                    <a href="{% url 'home' %}" class="button is-danger">Iniciar sesión</a>
                </span>
            </p>
        </footer>
    </div>
</div>
{% endblock contenido %}

templates/perfil.html
{% extends "base/base.html" %}
{% block contenido %}
<section class="hero is-warning is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title is-family-primary">
                Mi perfil.
            </h1>
            <h2 class="subtitle is-family-secondary has-text-justified">
                Consulta tus datos personales a continuación.
            </h2>
        </div>
    </div>
</section>

<section class="section">
    <div class="columns is-centered">
        <div class="column is-four-fifths">
            <div class="content">
                <div class="card">
                    <div class="card-content">
                        <div class="content">
                            <div class="columns is-centered">
                                <div class="column has-text-centered">
                                    <div class="subtitle is-family-primary is-5"><strong>Datos Personales:</strong>
                                    </div>
                                    <p><strong>Nombre de Usuario: </strong>{{user.username}}</p>
                                    <p><strong>Nombre: </strong>{{user.nombre}}</p>
                                    {% if user.apellido != "" and user.apellido != None %}
                                    <p><strong>Apellido: </strong>{{user.apellido}}</p>
                                    {% endif %}
                                    <p><strong>Sexo: </strong>{{user.get_sexo_display}}</p>
                                    <p><strong>Fecha de Nacimiento: </strong>{{user.fecha_nacimiento}}</p>
                                    <p><strong>Correo Electrónico: </strong>{{user.correo}}</p>
                                    <p><strong>Fecha de Registro: </strong>{{user.date_joined}}</p>
                                </div>
                                <div class="column has-text-centered">
                                    <div class="subtitle is-family-primary is-5"><strong>Datos de mi Organización:</strong>
                                    </div>
                                    <p><strong>Nombre: </strong>{{organizacion.nombre}}</p>
                                    <p><strong>Correo Electrónico: </strong>{{organizacion.correo}}</p>
                                    <p><strong>Ubicación: </strong>{{organizacion.ubicacion}}</p>
                                    <p><strong>Puesto: </strong>{{puesto}}</p>
                                </div>
                            </div>
                            <div class="has-text-centered">
                                <a href="{% url 'home' %}" class="button is-primary">Volver al Inicio</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock contenido %}

templates/procesar.html
{% extends "base/base.html" %}

{% block contenido %}
<section class="hero is-warning is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title is-family-primary">
                Procesar entrada
            </h1>
            <h2 class="subtitle is-family-secondary has-text-justified">
                Registra acá la asistencia al evento de parte de un usuario.
            </h2>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-6 is-centered">
            <div class="box has-text-centered">
                <form id="procesar" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="title is-5 is-family-secondary">
                        Sube un código QR a continuación.
                    </div>
                    <div class="input">
                        <input type="file" accept="image/*;capture=camera" name="qr" id="id_qr" required>
                        </input>
                    </div>
                    <div class="has-text-centered">
                        <br />
                        <input type="submit" class="button is-primary is-rounded" value="Verificar"/>
                    </div>
                    {% if form.non_field_errors %}
                    <br/>
                    <strong class="has-text-danger">{{form.non_field_errors}}</strong>
                    {% else %}
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock contenido %}

templates/registrar.html
{% extends "base/base.html" %}

{% block contenido %}
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title is-family-primary">
                Completar Registro
            </h1>
            <h2 class="subtitle is-family-secondary has-text-justified">
                A continuación podrás completar los datos para registrar.
            </h2>
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
        <div class="box">
            <article class="tile is-child has-text-justified" style="height: 85%;">
                <form id="signUp" method="POST">
                {% csrf_token %}
                {% if form.errors %}
                {% for error in form.errors %}
                {{error.message}}
                {% endfor %}
                {% else %}
                {% endif %}
                    <div class="field is-horizontal">
                        <div class="field-label is-normal">
                            <label class="label">Usuario: </label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input class="input" type="text" value="{{username}}" name="username"
                                        id="id_username" />
                                </p>
                            </div>
                        </div>

                        <div class="field-label is-normal">
                            <label class="label">Nombre: </label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input class="input" type="text" name="nombre" id="id_nombre" />
                                </p>
                            </div>
                        </div>

                        <div class="field-label is-normal">
                            <label class="label">Correo: </label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input class="input" type="email" value="{{email}}" name="correo" id="id_correo" />
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="field is-horizontal">
                        <div class="field-label is-normal">
                            <label class="label">Sexo: </label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <div class="select">
                                        <select name="sexo" id="id_sexo">
                                            <option value="M" selected>Masculino</option>
                                            <option value="F">Femenino</option>
                                            <option value="O">Otro</option>
                                        </select>
                                    </div>
                                </p>
                            </div>
                        </div>

                        <div class="field-label is-small">
                            <label class="label">Fecha de Nacimiento: </label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input class="input" type="date" name="fecha_nacimiento" id="id_fecha_nacimiento" />
                                </p>
                            </div>
                        </div>

                        <div class="field-label is-small">
                            <label class="label">Organización donde trabaja: </label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <div class="select">
                                        <select name="organizacion" id="id_organizacion">
                                            {% for organizacion in organizaciones %}
                                            <option value="{{organizacion.id}}">{{organizacion.nombre}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="field is-horizontal">
                        <div class="field-label is-normal">
                            <label class="label">Puesto: </label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input class="input" type="text" name="puesto" id="id_puesto" />
                                </p>
                            </div>
                        </div>

                        <div class="field-label is-normal">
                            <label class="label">Contraseña: </label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input class="input" type="password" name="password1" id="id_password1" />
                                </p>
                            </div>
                        </div>

                        <div class="field-label is-small">
                            <label class="label">Confirmar Contraseña: </label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input class="input" type="password" name="password2" id="id_password2" />
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="has-text-centered" style="height: 15%;">
                        <br />
                        <input type="submit" class="button is-info" value="Registrar" />
                    </div>
                </form>
            </article>
        </div>
    </div>
</section>
{% endblock %}